CREATE TABLE CART(
    P_NAME VARCHAR2(255) NOT NULL,
    M_ID VARCHAR2(255) NOT NULL,
    C_NO NUMBER(10) NOT NULL PRIMARY KEY,
    C_COUNT NUMBER(5) NOT NULL,
    C_PRICE NUMBER(10) NOT NULL
);

CREATE SEQUENCE SEQ_C_NO START WITH 1 INCREMENT BY 1;

CREATE TABLE P_ORDER(
    O_NO NUMBER(10) NOT NULL PRIMARY KEY,
    M_ID VARCHAR2(255) NOT NULL,
    O_DATE DATE DEFAULT SYSDATE NOT NULL,
    O_COUNT NUMBER(10) NOT NULL,
    O_PRICE NUMBER(10) NOT NULL,
    O_ADDR VARCHAR2(255) NOT NULL,
    O_NAME VARCHAR2(50) NOT NULL,
    P_NAME VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE SEQ_O_NUM START WITH 1 INCREMENT BY 1;

CREATE TABLE P_REVIEW(
    R_NO NUMBER(10) NOT NULL PRIMARY KEY,
    M_ID VARCHAR2(255) NOT NULL,
    R_CONTENT VARCHAR2(500) NOT NULL,
    R_REGDATE DATE DEFAULT SYSDATE NOT NULL,
    P_NAME VARCHAR2(255) NOT NULL
)

CREATE SEQUENCE SEQ_R_NO START WITH 1 INCREMENT BY 1;

CREATE TABLE PRODUCT(
    P_NO NUMBER(10) NOT NULL PRIMARY KEY,
    P_NAME VARCHAR2(255) NOT NULL,
    P_PRICE NUMBER(10),
    P_CONTENT VARCHAR2(255),
    P_STOCK NUMBER(10),
    P_IMG VARCHAR2(255)
)

CREATE SEQUENCE SEQ_P_NO START WITH 1 INCREMENT BY 1;

commit;

/*+        여기까지         */

alter table members add p_img varchar2(100);

commit;

update members set p_img='5585a567c95640e099ee6f5a2f70764d.JPG'
where mid = 'js';

select p_img from members where mid='js'; 


